### ISSUE TITLE
Scripts created above a certain size break the spacing of the generated printable

### ISSUE THREAD

**Issue by ErgoAsciiCat** [Tsubashi/botc_tokens#2]
Scripts with more than 18 roles break the generating script. The first 18 are ignored or stacked upon each other and the script continues generating role tokens properly with a bad offset for the first row.
The reminder tokens do not seem to have this issue but stress testing hasn't been done.

To recreate:
On Windows 11 - use the `botc_tokens group` command on a script containing 19+ roles.

Version: 
ImageMagick 7.1.1-29 Q16-HDRI x64 0deac72:20240225
botc_tokens, Version '2024.3.1'
Win 11 23H2

**Comment by Tsubashi** [comment]
Can you tell my personal use case is Teensyville scripts? I'm glad you reported this. I had added the capability for it to process multiple pages, but apparently forgot to increment the page count, so it just kept overwriting the previous one. It would happen with the reminders as well, if you ever needed a second page. I've push a commit to dev to fix this.
