### ISSUE TITLE
Update parameters?

### ISSUE THREAD

**Issue by violetcrestedwren** [Tsubashi/botc_tokens#7]
Hi there, less an issue and more a question: what parameters does the `update` command accept? I expected that it followed the wiki urls with the default being `Experimental`, thus it would take `Trouble_Brewing`, `Sects&Violets`, etc., but this doesn't seem to be the case. Any help is appreciated!

**Comment by Tsubashi** [comment]
If you run `botc_tokens update --help` it prints out its usage description. Here is what is shows currently:

```
usage: botc_tokens [-h] [-o OUTPUT_DIR] [--script-filter SCRIPT_FILTER] [--reminders REMINDERS] [-c CUSTOM_LIST]

Download roles from the wiki, with associated icon and description.

options:
  -h, --help            show this help message and exit
  -o OUTPUT_DIR, --output-dir OUTPUT_DIR
                        Directory in which to write the json and icon files (Default: 'inputs')
  --script-filter SCRIPT_FILTER
                        Filter for scripts to pull (Default: 'Experimental')
  --reminders REMINDERS
                        JSON file to override reminder guesses from the wiki.
  -c CUSTOM_LIST, --custom-list CUSTOM_LIST
                        JSON file with a custom list of roles to update.
```           

The parameter you are probably looking for is `script-filter` which defaults to experimental. This makes sure to only grab roles whose "version" tag include the specified word. If you want to download everything, you can set this parameter to an empty string (`""`)
